{% set version = "0.6.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rsnps
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rsnps_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsnps/rsnps_{{ version }}.tar.gz
  sha256: 22046736203b3101a2f487c60603299b7d6947c2a7cde829b4fcf1f8fb1781d3

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rjsonio
    - r-crul >=0.5.2
    - r-data.table
    - r-httr
    - r-jsonlite
    - r-plyr
    - r-stringr
  run:
    - r-base
    - r-rjsonio
    - r-crul >=0.5.2
    - r-data.table
    - r-httr
    - r-jsonlite
    - r-plyr
    - r-stringr

test:
  commands:
    - $R -e "library('rsnps')"           # [not win]
    - "\"%R%\" -e \"library('rsnps')\""  # [win]

about:
  home: https://github.com/ropensci/rsnps
  license: MIT
  summary: "A programmatic interface to various 'SNP' 'datasets' on the web: 'OpenSNP' (<https://opensnp.org>), and 'NBCIs' 'dbSNP' database (<https://www.ncbi.nlm.nih.gov/projects/SNP>). Functions are included for searching for 'NCBI'. For 'OpenSNP', functions are included for getting 'SNPs', and data for 'genotypes', 'phenotypes',
    annotations, and bulk downloads of data by user."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rsnps
# Title: Get 'SNP' ('Single-Nucleotide' 'Polymorphism') Data on the Web
# Description: A programmatic interface to various 'SNP' 'datasets' on the web: 'OpenSNP' (<https://opensnp.org>), and 'NBCIs' 'dbSNP' database (<https://www.ncbi.nlm.nih.gov/projects/SNP>). Functions are included for searching for 'NCBI'. For 'OpenSNP', functions are included for getting 'SNPs', and data for 'genotypes', 'phenotypes', annotations, and bulk downloads of data by user.
# Version: 0.3.0
# License: MIT + file LICENSE
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com", comment = c(ORCID = "0000-0003-1444-9135")), person("Kevin", "Ushey", role = "aut"), person("Hao", "Zhu", role = "aut") )
# URL: https://github.com/ropensci/rsnps
# BugReports: https://github.com/ropensci/rsnps/issues
# VignetteBuilder: knitr
# Encoding: UTF-8
# Imports: plyr, stringr, crul (>= 0.5.2), data.table, XML, xml2, jsonlite
# Suggests: testthat, knitr
# RoxygenNote: 6.1.0
# NeedsCompilation: no
# Packaged: 2018-09-19 23:27:52 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>), Kevin Ushey [aut], Hao Zhu [aut]
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-09-20 04:50:03 UTC
